// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://xwvegdqetuldzcpplkjx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3dmVnZHFldHVsZHpjcHBsa2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNjQ4MjMsImV4cCI6MjA0ODc0MDgyM30.oSKRfc5n7uSLefU_UlxZ87yKgODX3oeibfLRA7LlXxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);